version: '3.3'

services:
  postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - ./postgresdb:/var/lib/postgresql/data



  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin


  mysql:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${POSTGRES_DB}
        MYSQL_USER: ${POSTGRES_USER}
        MYSQL_PASSWORD: ${POSTGRES_PASSWORD}
        MYSQL_PORT: ${POSTGRES_PORT}
    ports:
        - 3306:3306
    volumes:
        - ./MYSQLdb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        PMA_HOST: ${POSTGRES_DB}


    ports:
        - 8080:80
    volumes:
        - ./phpmyadmin:/var/lib/phpmyadmin
